CREATE DATABASE IF NOT EXISTS HOTEL_DB;

USE DATABASE HOTEL_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE DATABASE HOTEL_DB;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE hotel_stage;

LIST @hotel_stage;

SELECT COUNT(*) 
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;

USE DATABASE HOTEL_DB;
USE SCHEMA RAW;

SELECT COUNT(*) FROM HOTEL_BOOKINGS_RAW;
SELECT * FROM HOTEL_BOOKINGS_RAW LIMIT 5;

select * from hotel_bookings_raw;

SELECT COUNT(*) AS total_bookings
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;


DESC TABLE HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;

SHOW COLUMNS IN TABLE HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;

SELECT COUNT(*) AS total_bookings
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;

SELECT
    BOOKING_STATUS,
    COUNT(*) AS booking_count
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
GROUP BY BOOKING_STATUS;

SELECT
    ROUND(
        SUM(CASE WHEN BOOKING_STATUS = 'Cancelled' THEN 1 ELSE 0 END)
        * 100.0 / COUNT(*),
        2
    ) AS cancellation_percentage
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;

SELECT
    HOTEL_CITY,
    COUNT(*) AS total_bookings
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
GROUP BY HOTEL_CITY
ORDER BY total_bookings DESC;

SELECT
    HOTEL_CITY,currency,
    ROUND(SUM(TOTAL_AMOUNT), 2) AS total_revenue
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
WHERE BOOKING_STATUS = 'Confirmed'
GROUP BY HOTEL_CITY,currency
ORDER BY total_revenue DESC;

SELECT
    HOTEL_CITY,currency,
    ROUND(SUM(TOTAL_AMOUNT), 2) AS total_revenue
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
WHERE BOOKING_STATUS = 'Confirmed'
GROUP BY currency, HOTEL_CITY
ORDER BY total_revenue DESC;

SELECT
    HOTEL_CITY,
    ROUND(SUM(TOTAL_AMOUNT), 2) AS total_revenue
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
WHERE BOOKING_STATUS = 'Confirmed'
GROUP BY HOTEL_CITY
ORDER BY total_revenue DESC;

SELECT
    ROOM_TYPE,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS avg_amount
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
WHERE BOOKING_STATUS = 'Confirmed'
GROUP BY ROOM_TYPE;

SELECT
    NUM_GUESTS,
    COUNT(*) AS bookings
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
GROUP BY NUM_GUESTS
ORDER BY NUM_GUESTS;

-- ANALYTICS views

USE DATABASE HOTEL_DB;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

CREATE OR REPLACE VIEW ANALYTICS.V_BOOKINGS_CLEAN AS
SELECT
    BOOKING_ID,
    HOTEL_ID,
    HOTEL_CITY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_EMAIL,
    CHECK_IN_DATE,
    CHECK_OUT_DATE,
    ROOM_TYPE,
    NUM_GUESTS,
    TOTAL_AMOUNT,
    CURRENCY,
    BOOKING_STATUS
FROM RAW.HOTEL_BOOKINGS_RAW
WHERE HOTEL_CITY IS NOT NULL
  AND TOTAL_AMOUNT IS NOT NULL;

SELECT * FROM ANALYTICS.V_BOOKINGS_CLEAN;

SELECT * FROM ANALYTICS.V_BOOKINGS_CLEAN LIMIT 5;

CREATE OR REPLACE VIEW ANALYTICS.V_CONFIRMED_BOOKINGS AS
SELECT *
FROM ANALYTICS.V_BOOKINGS_CLEAN
WHERE BOOKING_STATUS = 'Confirmed';

SELECT * FROM ANALYTICS.V_CONFIRMED_BOOKINGS;

CREATE OR REPLACE VIEW ANALYTICS.V_CANCELLED_BOOKINGS AS
SELECT *
FROM ANALYTICS.V_BOOKINGS_CLEAN
WHERE BOOKING_STATUS = 'Cancelled';

SELECT * FROM ANALYTICS.V_CANCELLED_BOOKINGS;

SELECT COUNT(*) FROM ANALYTICS.V_CONFIRMED_BOOKINGS;
SELECT COUNT(*) FROM ANALYTICS.V_CANCELLED_BOOKINGS;

CREATE OR REPLACE VIEW ANALYTICS.V_CITY_REVENUE_SUMMARY AS
SELECT
    HOTEL_CITY,
    COUNT(*) AS total_bookings,
    SUM(TOTAL_AMOUNT) AS total_revenue,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS avg_booking_amount
FROM ANALYTICS.V_CONFIRMED_BOOKINGS
GROUP BY HOTEL_CITY
ORDER BY total_revenue DESC;

SELECT * FROM ANALYTICS.V_CITY_REVENUE_SUMMARY;

SELECT * FROM ANALYTICS.V_CITY_REVENUE_SUMMARY LIMIT 10;

CREATE OR REPLACE VIEW ANALYTICS.V_ROOMTYPE_SUMMARY AS
SELECT
    ROOM_TYPE,
    COUNT(*) AS total_bookings,
    SUM(TOTAL_AMOUNT) AS total_revenue,
    ROUND(AVG(TOTAL_AMOUNT), 2) AS avg_booking_amount
FROM ANALYTICS.V_CONFIRMED_BOOKINGS
GROUP BY ROOM_TYPE
ORDER BY total_revenue DESC;

SELECT * FROM ANALYTICS.V_ROOMTYPE_SUMMARY;

WITH city_revenue AS (
    SELECT
        HOTEL_CITY,
        SUM(TOTAL_AMOUNT) AS total_revenue
    FROM ANALYTICS.V_CONFIRMED_BOOKINGS
    GROUP BY HOTEL_CITY
)
SELECT
    HOTEL_CITY,
    ROUND(total_revenue, 2) AS total_revenue
FROM city_revenue
ORDER BY total_revenue DESC;

WITH city_revenue AS (
    SELECT
        HOTEL_CITY,
        SUM(TOTAL_AMOUNT) AS total_revenue
    FROM ANALYTICS.V_CONFIRMED_BOOKINGS
    GROUP BY HOTEL_CITY
)
SELECT
    HOTEL_CITY,
    ROUND(total_revenue, 2) AS total_revenue
FROM city_revenue
WHERE total_revenue > 200   -- smaller value
ORDER BY total_revenue DESC;

WITH city_revenue AS (
    SELECT
        HOTEL_CITY,
        SUM(TOTAL_AMOUNT) AS total_revenue
    FROM ANALYTICS.V_CONFIRMED_BOOKINGS
    GROUP BY HOTEL_CITY
)
SELECT
    HOTEL_CITY,
    ROUND(total_revenue, 2) AS total_revenue
FROM city_revenue
WHERE total_revenue > 500   -- smaller value
ORDER BY total_revenue DESC;

USE DATABASE HOTEL_DB;

SELECT
    HOTEL_CITY,
    BOOKING_ID,
    ROOM_TYPE,
    NUM_GUESTS,
    TOTAL_AMOUNT,
    RANK() OVER (
        PARTITION BY HOTEL_CITY
        ORDER BY TOTAL_AMOUNT DESC
    ) AS booking_rank_in_city
FROM ANALYTICS.V_CONFIRMED_BOOKINGS
QUALIFY booking_rank_in_city <= 3
ORDER BY HOTEL_CITY, booking_rank_in_city;

WITH daily_revenue AS (
    SELECT
        TO_DATE(CHECK_IN_DATE, 'YYYY-MM-DD') AS check_in_dt,
        SUM(TOTAL_AMOUNT) AS day_revenue
    FROM ANALYTICS.V_CONFIRMED_BOOKINGS
    GROUP BY check_in_dt
)
SELECT
    check_in_dt,
    day_revenue,
    SUM(day_revenue) OVER (
        ORDER BY check_in_dt
    ) AS cumulative_revenue
FROM daily_revenue
ORDER BY check_in_dt;

SELECT CHECK_IN_DATE
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
LIMIT 5;

SELECT CHECK_IN_DATE
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW;

SELECT
    CHECK_IN_DATE,
    CASE
        WHEN TRY_TO_DATE(CHECK_IN_DATE, 'DD/MM/YYYY') IS NOT NULL
            THEN TRY_TO_DATE(CHECK_IN_DATE, 'DD/MM/YYYY')
        WHEN TRY_TO_DATE(CHECK_IN_DATE, 'MM/DD/YYYY') IS NOT NULL
            THEN TRY_TO_DATE(CHECK_IN_DATE, 'MM/DD/YYYY')
        WHEN TRY_TO_DATE(CHECK_IN_DATE, 'DD-MM-YYYY') IS NOT NULL
            THEN TRY_TO_DATE(CHECK_IN_DATE, 'DD-MM-YYYY')
        ELSE NULL
    END AS parsed_check_in_date
FROM HOTEL_DB.RAW.HOTEL_BOOKINGS_RAW
LIMIT 20;

CREATE OR REPLACE VIEW HOTEL_DB.ANALYTICS.V_CONFIRMED_BOOKINGS_CLEAN_DATES AS
SELECT
    *,
    CASE
        WHEN TRY_TO_DATE(CHECK_IN_DATE, 'DD/MM/YYYY') IS NOT NULL
            THEN TRY_TO_DATE(CHECK_IN_DATE, 'DD/MM/YYYY')
        WHEN TRY_TO_DATE(CHECK_IN_DATE, 'MM/DD/YYYY') IS NOT NULL
            THEN TRY_TO_DATE(CHECK_IN_DATE, 'MM/DD/YYYY')
        WHEN TRY_TO_DATE(CHECK_IN_DATE, 'DD-MM-YYYY') IS NOT NULL
            THEN TRY_TO_DATE(CHECK_IN_DATE, 'DD-MM-YYYY')
        ELSE NULL
    END AS CHECK_IN_DT
FROM HOTEL_DB.ANALYTICS.V_CONFIRMED_BOOKINGS;


WITH daily_revenue AS (
    SELECT
        CHECK_IN_DT,
        SUM(TOTAL_AMOUNT) AS day_revenue
    FROM HOTEL_DB.ANALYTICS.V_CONFIRMED_BOOKINGS_CLEAN_DATES
    WHERE CHECK_IN_DT IS NOT NULL
    GROUP BY CHECK_IN_DT
)
SELECT
    CHECK_IN_DT,
    day_revenue,
    SUM(day_revenue) OVER (ORDER BY CHECK_IN_DT) AS cumulative_revenue
FROM daily_revenue
ORDER BY CHECK_IN_DT;


SELECT *
FROM HOTEL_DB.ANALYTICS.V_CONFIRMED_BOOKINGS;




















  

















